name: Metadata Platform Extractor Test

on:
  workflow_dispatch:

jobs:
  run-extractor:
    runs-on: self-hosted

    steps:
      - name: Check Python version
        run: |
          python --version

      - name: Check current folder
        run: |
          pwd
          dir